### ISSUE TITLE
Modifications and improvements task list!

### ISSUE THREAD

**Issue by edif** [edif/Pomodoro#1]
- [ ] Make the window of the program start at the center of the screen and with a standard resolution
- [ ] Better organize the layout
- [ ] Implement a feature to save the time for work and break sessions so that users don't have to enter it every time they start the program
- [ ] Add a feature that allows users to start a new work session or break session without having to reset the program
- [ ] Add a feature that allows users to pause and resume the countdown timer
- [ ] Add a feature that notifies the user when the work session or break session is over
- [ ] Add a feature that tracks the number of completed work sessions and break sessions
- [ ] Add a feature that allows users to customize the appearance of the program, such as changing the background color or font
- [ ] Add a feature that allows users to set reminders to take a break or start a new work session
